### ISSUE TITLE
Suggestion: Key Ring's key sanity. 

### ISSUE THREAD

**Issue by Cheetoyumyum** [ZoeyZolotova/mm-rando#160]
Idea taken from Oot Randomizer. 
I really enjoyed this playthrough

> Selected dungeons will have all of their keys found
> at once in a ring rather than individually.
> 
> For example, instead of shuffling 5 Forest Temple
> small keys into the pool, you will find a single
> key ring which will give you all 5 keys at once.
> 
> Selecting key ring for dungeons will have no effect
> if Small Keys are set to Remove or Vanilla.
> 
> Selecting key ring for Thieves' Hideout will have
> no effect if Thieves' Hideout keys are in vanilla
> locations or Gerudo's Fortress is set to Rescue
> One Carpenter

**Comment by ZoeyZolotova** [comment]
It's not really worth it considering only two dungeons have more than one small key, and even for them you really only need one or two of them.

In the future, I'd prefer suggestions to be made through the suggestions channel in discord, so that there can be more community participation in the conversation.
