### ISSUE TITLE
Freeze at getting song from ranch if you fail the alien invasion

### ISSUE THREAD

**Issue by DuskHawk** [ZoeyZolotova/mm-rando#5]
doesn't matter which core you use when you receive the song, it freezes

**Comment by ZoeyZolotova** [comment]
If you fail the alien invasion, isn't Romani supposed to be really depressed and not let you do anything with Epona? Vanilla-wise that's why you need the powder keg to get epona.

**Comment by DuskHawk** [comment]
no, you get eponas song for doing the run of riding around on epona and shooting the fake aliens

**Comment by EvilApple567** [comment]
I remember having this issue once (crash upon getting Epona Song pickup), and it was because I had already gotten the pickup. I'm not sure why the game crashed there, perhaps the placeholder item for after you get ES was removed/modified (The pickup was the Captain's Hat I remember). This was a while ago and I know I'm not being super helpful just spitballing from an experience, but crashes in MM are particularly brutal so anything to further investigation/development is welcomed I hope.

**Comment by ZoeyZolotova** [comment]
Closing this as there's not enough clear information. Feel free to reopen if there's still an issue after 1.9 is released.
