### ISSUE TITLE
Suggestion: Exclude Locations From Logic

### ISSUE THREAD

**Issue by aplumafreak500** [ZoeyZolotova/mm-rando#62]
Title explains. Some emulators and/or graphics plugins don't handle the Lens of Truth properly, so it would be nice to be able to exclude the Goron Mask location from logic so as to prevent progression items from being present there.

Also, it would allow the two Shooting Gallery's prizes to not be progression items (I speak for a lot of fans when I say that the Town Shooting Gallery in particular is not worth the time in race environments).

Thanks for your consideration!

**Comment by zmarotrix** [comment]
While disabling required locations is a feature that is requested and talked about amongst the dev team, we want to totally rework how the logic works first. We also don't plan to remove anything from logic because of faulty emulation, especially when it's an easy thing to fix. However, if you are for some reason against getting a functioning emulator, we do offer a logic editor that gives you the ability to make your own custom logic with whatever you want in or out of logic. 

As for Shooting galleries, the same info applies. If you simply want to exclude something from logic needed to beat the game but still have it randomized, you can apply Moon Access as a requirement and it should never be required to beat the game. On the topic of races, we have already been in contact with top runners of both OoT and MM and we have come to the conclusion that while double minigames are accessive, all minigames should be included for their first reward. This is handled by a custom item list string pinned in the discords racing channel.

Again, thank you for the feedback!
